// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZTQzzWD7SiMCGlwIyrxkgqbBnbN05maU',
    appId: '1:366047220818:web:1c5196f9705471ca34bb8b',
    messagingSenderId: '366047220818',
    projectId: 'samsung-db-9d686',
    authDomain: 'samsung-db-9d686.firebaseapp.com',
    storageBucket: 'samsung-db-9d686.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXRiUBnqvqX6VHZz7fUVl1yiC5ogQnSo4',
    appId: '1:366047220818:android:6c3c745eb001a42c34bb8b',
    messagingSenderId: '366047220818',
    projectId: 'samsung-db-9d686',
    storageBucket: 'samsung-db-9d686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU-kSX8eXiXIlkHHcX2hyigecQ9SY1QOw',
    appId: '1:366047220818:ios:a34b80e0a5691f1e34bb8b',
    messagingSenderId: '366047220818',
    projectId: 'samsung-db-9d686',
    storageBucket: 'samsung-db-9d686.appspot.com',
    iosClientId: '366047220818-r5an59ojf2p19l6b9tr0kmmgr98ui4ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.samsug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU-kSX8eXiXIlkHHcX2hyigecQ9SY1QOw',
    appId: '1:366047220818:ios:a34b80e0a5691f1e34bb8b',
    messagingSenderId: '366047220818',
    projectId: 'samsung-db-9d686',
    storageBucket: 'samsung-db-9d686.appspot.com',
    iosClientId: '366047220818-r5an59ojf2p19l6b9tr0kmmgr98ui4ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.samsug',
  );
}
